name: coronastats
description: A new Flutter application.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  http: ^0.12.2
  intl: ^0.16.1
  google_maps_flutter: ^1.0.6
  firebase_core: ^0.5.1
  firebase_auth: ^0.18.2
  cloud_firestore: ^0.14.2
  modal_progress_hud: ^0.1.3
  provider: ^4.3.2+2
  url_launcher: ^5.7.10
  mailto: ^1.0.0
  font_awesome_flutter: ^8.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  
  assets:
  - images/
  
  fonts:
     - family: Mukta
       fonts:
         - asset: fonts/Mukta-Regular.ttf
         - asset: fonts/Mukta-SemiBold.ttf

     - family: PopR
       fonts:
         - asset: fonts/Poppins-Regular.ttf

     - family: PopM
       fonts:
         - asset: fonts/Poppins-Medium.ttf

     - family: PopS
       fonts:
         - asset: fonts/Poppins-SemiBold.ttf

     - family: PopB
       fonts:
         - asset: fonts/Poppins-Bold.ttf
